export const SHOW_NEWPREJECTPOP = 'SHOW_NEWPREJECTPOP';
export const ENTER_NEWPOP = 'SHOW_NEWPREJECTPOP';
export const GET_ITMELISTS='GET_ITMELISTS';

// yun
export const DETAILS_CHANGE='DETAILS_CHANGE';
export const TASKTITLE_CHANGE='TASKTITLE_CHANGE';
export const TASKSTAR_CHANGE='TASKSTAR_CHANGE';
export const TASKREMIND_CHANGE='TASKREMIND_CHANGE';
export const TASKITEM_CHANGE='TASKITEM_CHANGE';
export const DEMO_CHANGE='DEMO_CHANGE';
export const TASK_POSITION = 'TASK_POSITION';
export const TASK_LIST = 'TASK_LIST';
export const TASK_INDEX = 'TASK_INDEX';
export const TASKTIME_CHANGE = 'TASKTIME_CHANGE';
export const PROJECT_CHANGE = 'PROJECT_CHANGE';
export const TASKDELCHANGE = 'TASKDELCHANGE';

// new_yun
export const CHECKEDLIST_CHANGE = 'CHECKEDLIST_CHANGE';
export const FILELENGTH_CHANGE = 'FILELENGTH_CHANGE';
export const TASKIDS_CHANGE = 'TASKIDS_CHANGE';
